/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import {useGLTF, useScroll} from "@react-three/drei";
import * as THREE from "three";
// @ts-ignore
export function Clocks(props) {
  // @ts-ignore
  const {nodes, materials} = useGLTF("./models/clocks.gltf");
  console.log({nodes})
  const baseMaterial = <meshStandardMaterial color={"#ffffff"}
                                             side={THREE.DoubleSide}
                                             roughness={0.5}/>

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Stand.geometry}
        position={[1.65, 0.406, -0.306]}
      >
        {baseMaterial}
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Magnet_1_border.geometry}
        position={[1.14, 0.591, -0.461]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.156, 0.053, 0.156]}
      >
        {baseMaterial}
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Magnet_1.geometry}
        position={[1.14, 0.591, -0.461]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.136, 0.05, 0.136]}
      >
        {baseMaterial}
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Magnet_2_border.geometry}
        position={[-1.149, 0.591, -0.461]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.156, 0.053, 0.156]}
      >
        {baseMaterial}
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Magnet_2.geometry}
        position={[-1.149, 0.591, -0.461]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.136, 0.05, 0.136]}
      >
        {baseMaterial}
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Back_base.geometry}
        position={[0, 0.225, -0.277]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        {baseMaterial}
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mute_btn_base.geometry}
        position={[1.719, -0.043, -0.124]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
        scale={[0.066, 0.073, 0.073]}
      >
        {baseMaterial}
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mute_btn_top.geometry}
        position={[1.741, -0.043, -0.124]}
        rotation={[-Math.PI, 0, -Math.PI / 2]}
        scale={[0.073, 0.073, 0.066]}
      >
        {baseMaterial}
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Button_1.geometry}
        position={[-1.215, -0.651, 0.124]}
      >
        {baseMaterial}
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Button_2.geometry}
        position={[-0.577, -0.651, 0.124]}
      >
        {baseMaterial}
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Button_3.geometry}
        position={[0.03, -0.651, 0.124]}
      >
        {baseMaterial}
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Button_4.geometry}
        position={[0.649, -0.65, 0.126]}
      >
        {baseMaterial}
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Base.geometry}
        rotation={[Math.PI / 2, 0, 0]}
      >
        {baseMaterial}
      </mesh>
    </group>
  );
}

useGLTF.preload("./models/clocks.gltf");
